/**
 * LA8159-AI Endpoint Configuration
 * Full gateway catalog — 19 service categories
 * Auto-expanded from LA8159-ai-gateway-mcp-tools.md
 */

window.Olivia_ENDPOINTS = [

  /* ── 1. Gateway & Infrastructure ───────────────────────────── */
  { p: "/ping", m: "GET", t: "Gateway", s: "Liveness probe", d: "Lightweight liveness probe; does not check upstream services" },
  { p: "/health", m: "GET", t: "Gateway", s: "Health check", d: "Standard health check payload for service managers" },
  { p: "/health/aggregate", m: "GET", t: "Gateway", s: "Aggregated health", d: "Check health of all registered backend services with per-service details" },
  { p: "/services", m: "GET", t: "Gateway", s: "List services", d: "List all services registered in the gateway with connection info" },
  { p: "/api/gateway/routes", m: "GET", t: "Gateway", s: "Route catalog", d: "Consolidated route catalog from all registered services' OpenAPI specs" },
  { p: "/api/docs/endpoints", m: "GET", t: "Gateway", s: "Endpoint registry", d: "Normalized endpoint catalog consumed by frontend and ops tooling" },
  { p: "/api/docs/frontend", m: "GET", t: "Gateway", s: "Frontend registry", d: "Canonical frontend mounts and compatibility aliases" },
  { p: "/info", m: "GET", t: "Gateway", s: "Gateway info", d: "Gateway information and available endpoints summary" },

  /* ── 2. Authentication ─────────────────────────────────────── */
  { p: "/auth/login", m: "POST", t: "Authentication", s: "Login", d: "Authenticate with username/password and receive a JWT token" },
  { p: "/auth/refresh", m: "POST", t: "Authentication", s: "Refresh token", d: "Refresh an expiring token; returns new token with extended expiry" },
  { p: "/auth/me", m: "GET", t: "Authentication", s: "Current user", d: "Get information about the currently authenticated user" },
  { p: "/auth/logout", m: "POST", t: "Authentication", s: "Logout", d: "Logout endpoint; client should discard the token" },
  { p: "/auth/status", m: "GET", t: "Authentication", s: "Auth status", d: "Check if the current request is authenticated" },

  /* ── 3. Agents ─────────────────────────────────────────────── */
  { p: "/api/agents/stream", m: "POST", t: "Agents", s: "General agent stream", d: "Start a general-purpose agent SSE stream (step, tool_call, tool_result, done)" },
  { p: "/api/agents/guided/stream", m: "POST", t: "Agents", s: "Guided agent stream", d: "Start a guided agent with pause/resume; emits awaiting_guidance events" },
  { p: "/api/agents/guided/resume", m: "POST", t: "Agents", s: "Resume guided agent", d: "Resume a paused guided agent with guidance text" },
  { p: "/api/agents/guided/stop", m: "POST", t: "Agents", s: "Stop guided agent", d: "Stop the guided agent" },
  { p: "/api/agents/auditor/stream", m: "POST", t: "Agents", s: "Auditor agent stream", d: "Start architectural auditor with step protocol traceability" },
  { p: "/api/agents/auditor/pause", m: "POST", t: "Agents", s: "Pause auditor", d: "Pause the auditor agent at the next checkpoint" },
  { p: "/api/agents/auditor/resume", m: "POST", t: "Agents", s: "Resume auditor", d: "Resume a paused auditor agent with guidance" },
  { p: "/api/agents/auditor/stop", m: "POST", t: "Agents", s: "Stop auditor", d: "Stop the auditor agent" },
  { p: "/api/agents/stop", m: "POST", t: "Agents", s: "Stop agent (general)", d: "Stop any currently running agent" },
  { p: "/api/agents/create", m: "POST", t: "Agents", s: "Create agent", d: "Create new agent with isolated memory, Qdrant collection, and workspace" },
  { p: "/api/agents/list", m: "GET", t: "Agents", s: "List agents", d: "List all registered agents" },
  { p: "/api/agents/{id}", m: "GET", t: "Agents", s: "Get agent", d: "Get details for a specific agent by ID" },
  { p: "/api/agents/{id}", m: "DELETE", t: "Agents", s: "Delete agent", d: "Delete agent and clean up all resources" },
  { p: "/api/agents/{id}/activate", m: "POST", t: "Agents", s: "Activate agent", d: "Load agent into memory as the active agent" },
  { p: "/api/agents/models/catalog", m: "GET", t: "Agents", s: "Model catalog", d: "Get available AI models with pricing information" },
  { p: "/api/agents/models/switch", m: "POST", t: "Agents", s: "Switch model", d: "Switch the active model for subsequent agent requests" },

  /* ── 4. Legal Intelligence ─────────────────────────────────── */
  { p: "/api/legal/frameworks", m: "GET", t: "Legal Intelligence", s: "List frameworks", d: "List all registered legal frameworks with code, name, article count, jurisdiction" },
  { p: "/api/legal/frameworks/{code}", m: "GET", t: "Legal Intelligence", s: "Framework articles", d: "Get all articles for a specific legal framework by code" },
  { p: "/api/legal/frameworks/{code}/filter", m: "GET", t: "Legal Intelligence", s: "Filter articles", d: "Filter articles within a framework by theme or keyword text search" },
  { p: "/api/legal/search", m: "POST", t: "Legal Intelligence", s: "Semantic article search", d: "Semantic search across all legal articles using Qdrant vector search" },
  { p: "/api/legal/match", m: "POST", t: "Legal Intelligence", s: "Match transcript (SSE)", d: "AI-powered transcript → legal articles mapping via SSE stream" },
  { p: "/api/legal/build-framework", m: "POST", t: "Legal Intelligence", s: "Build framework", d: "Build a new legal framework from configuration JSON" },
  { p: "/api/legal/generate-config", m: "POST", t: "Legal Intelligence", s: "Generate config (SSE)", d: "Generate framework config from raw legal text using AI; returns SSE stream" },
  { p: "/api/legal/extract-pdf", m: "POST", t: "Legal Intelligence", s: "Extract PDF text", d: "Extract text content from a PDF file for framework building" },
  { p: "/api/legal/ontology/summary", m: "GET", t: "Legal Intelligence", s: "Ontology summary", d: "Get summary of the legal ontology structure" },
  { p: "/api/legal/pack/build", m: "POST", t: "Legal Intelligence", s: "Build compliance pack", d: "Build pre-computed compliance analysis pack for a framework" },

  /* ── 5. Legal Pipeline (ARGUS) ─────────────────────────────── */
  { p: "/api/pipeline/run", m: "POST", t: "Pipeline", s: "Run ARGUS pipeline", d: "Execute full 7-stage ARGUS legal analysis pipeline" },
  { p: "/api/pipeline/cases/{id}", m: "GET", t: "Pipeline", s: "Get case", d: "Get stored case entity for a case ID" },
  { p: "/api/pipeline/cases/{id}/analyze", m: "POST", t: "Pipeline", s: "Analyze case", d: "Trigger full analysis run for a case" },
  { p: "/api/pipeline/cases/{id}/transcripts", m: "GET", t: "Pipeline", s: "Case transcripts", d: "List transcripts for a case (lightweight metadata)" },
  { p: "/api/pipeline/argus/analyze", m: "POST", t: "Pipeline", s: "ARGUS analyze transcript", d: "Submit transcript for ARGUS legal analysis; returns session_id" },
  { p: "/api/pipeline/argus/sessions/{id}", m: "GET", t: "Pipeline", s: "ARGUS session status", d: "Get status and results of an ARGUS analysis session" },
  { p: "/api/pipeline/argus/sessions/{id}/results", m: "GET", t: "Pipeline", s: "ARGUS session results", d: "Get full results of a completed ARGUS analysis" },
  { p: "/api/pipeline/dashboard/directories", m: "GET", t: "Pipeline", s: "Dashboard directories", d: "Get list of available data directories" },
  { p: "/api/pipeline/dashboard/directories/{key}", m: "GET", t: "Pipeline", s: "Directory contents", d: "Get contents of a specific data directory" },
  { p: "/api/pipeline/dashboard/stats", m: "GET", t: "Pipeline", s: "Dashboard stats", d: "Get aggregated statistics for the pipeline dashboard" },
  { p: "/api/pipeline/dashboard/search", m: "GET", t: "Pipeline", s: "Dashboard search", d: "Search across pipeline dashboard data" },
  { p: "/api/pipeline/health", m: "GET", t: "Pipeline", s: "Pipeline health", d: "Check LegalPipeline service health" },

  /* ── 6. Vector Memory & Graph ──────────────────────────────── */
  { p: "/api/memory/search", m: "POST", t: "Vector Memory", s: "Semantic search", d: "AI-First retrieval across vector collections; score ≥ 0.72 = high-quality" },
  { p: "/api/memory/context", m: "POST", t: "Vector Memory", s: "Assemble context", d: "Multi-collection search with Neo4j graph expansion" },
  { p: "/api/memory/ingest", m: "POST", t: "Vector Memory", s: "Ingest document", d: "Chunk, embed, and store document in Qdrant" },
  { p: "/api/memory/ingest-file", m: "POST", t: "Vector Memory", s: "Ingest file by path", d: "Ingest file by server path; auto-detects collection from extension" },
  { p: "/api/memory/ingest-upload", m: "POST", t: "Vector Memory", s: "Ingest upload", d: "Upload and ingest a document file directly (multipart)" },
  { p: "/api/memory/collections", m: "GET", t: "Vector Memory", s: "List collections", d: "List all Qdrant collections with metadata" },
  { p: "/api/memory/collections", m: "POST", t: "Vector Memory", s: "Create collection", d: "Create a new Qdrant collection with vector params" },
  { p: "/api/memory/collections/{name}", m: "GET", t: "Vector Memory", s: "Get collection", d: "Get detailed information about a specific collection" },
  { p: "/api/memory/collections/{name}", m: "DELETE", t: "Vector Memory", s: "Delete collection", d: "Delete a Qdrant collection and all its data" },
  { p: "/api/memory/graph/stats", m: "GET", t: "Vector Memory", s: "Graph statistics", d: "Get Neo4j graph statistics (node counts, relationships)" },
  { p: "/api/memory/graph/query", m: "POST", t: "Vector Memory", s: "Graph query", d: "Execute named Cypher query template against Neo4j" },
  { p: "/api/memory/graph/files", m: "GET", t: "Vector Memory", s: "Graph files", d: "List all files tracked in the Neo4j graph" },
  { p: "/api/memory/graph/entities", m: "GET", t: "Vector Memory", s: "Graph entities", d: "List all entities (people, organizations, concepts) in the graph" },
  { p: "/api/memory/agent/store", m: "POST", t: "Vector Memory", s: "Agent store", d: "Store an agent interaction in vector memory" },
  { p: "/api/memory/agent/recall", m: "POST", t: "Vector Memory", s: "Agent recall", d: "Recall relevant memories for an agent via semantic search" },
  { p: "/api/memory/health", m: "GET", t: "Vector Memory", s: "Memory health", d: "Check health of Qdrant and Neo4j connections" },

  /* ── 7. AI-First Compliance ────────────────────────────────── */
  { p: "/api/compliance/sessions", m: "GET", t: "Compliance", s: "List sessions", d: "List all active AI-First compliance sessions with compliance rate" },
  { p: "/api/compliance/sessions/{id}", m: "GET", t: "Compliance", s: "Session report", d: "Detailed compliance report: retrieval attempts, file accesses, violations" },
  { p: "/api/compliance/violations", m: "GET", t: "Compliance", s: "List violations", d: "All AI-First violations across sessions, newest first" },
  { p: "/api/compliance/stats", m: "GET", t: "Compliance", s: "Compliance stats", d: "Aggregate stats: total sessions, file accesses, violations, compliance rate" },
  { p: "/api/compliance/check/file", m: "POST", t: "Compliance", s: "Check file access", d: "Dry-run check if a file access would be AI-First compliant" },
  { p: "/api/compliance/check/tool", m: "POST", t: "Compliance", s: "Check tool call", d: "Dry-run check if a tool call would be AI-First compliant" },
  { p: "/api/compliance/record/retrieval", m: "POST", t: "Compliance", s: "Record retrieval", d: "Record retrieval results for a session; updates file coverage map" },
  { p: "/api/compliance/config", m: "GET", t: "Compliance", s: "Enforcement config", d: "Get current AI-First enforcement configuration" },

  /* ── 8. Step Protocol (Cost Tracking) ──────────────────────── */
  { p: "/api/steps/sessions", m: "GET", t: "Step Protocol", s: "List sessions", d: "List all active Step Protocol sessions with step count and cost" },
  { p: "/api/steps/sessions/{id}", m: "GET", t: "Step Protocol", s: "Get session", d: "Detailed session info including all steps with token/cost data" },
  { p: "/api/steps/sessions/{id}", m: "DELETE", t: "Step Protocol", s: "Remove session", d: "Remove a session from tracking" },
  { p: "/api/steps/sessions/{id}/cost", m: "GET", t: "Step Protocol", s: "Session cost", d: "Cost breakdown for a session by service" },
  { p: "/api/steps/sessions/{id}/complete", m: "POST", t: "Step Protocol", s: "Complete session", d: "Mark a session as completed" },
  { p: "/api/steps/cost/total", m: "GET", t: "Step Protocol", s: "Total cost", d: "Total cost across all active sessions" },
  { p: "/api/steps/cost/by-service", m: "GET", t: "Step Protocol", s: "Cost by service", d: "Cost breakdown by service across all sessions" },
  { p: "/api/steps/cost/by-model", m: "GET", t: "Step Protocol", s: "Cost by model", d: "Cost breakdown by AI model across all sessions" },
  { p: "/api/steps/pricing", m: "GET", t: "Step Protocol", s: "Pricing config", d: "Get current model pricing configuration" },
  { p: "/api/steps/calculate", m: "POST", t: "Step Protocol", s: "Calculate cost", d: "Calculate cost for given token counts; useful for pre-estimation" },
  { p: "/api/steps/health", m: "GET", t: "Step Protocol", s: "Steps health", d: "Check Step Protocol tracking health" },

  /* ── 9. Operations Dashboard ───────────────────────────────── */
  { p: "/api/ops/services", m: "GET", t: "Operations", s: "List services", d: "All registered services with status, port, and health" },
  { p: "/api/ops/services/{id}", m: "GET", t: "Operations", s: "Get service", d: "Detailed information about a specific service" },
  { p: "/api/ops/services/{id}/action", m: "POST", t: "Operations", s: "Service action 🔒", d: "Start, stop, or restart a service (admin auth required)" },
  { p: "/api/ops/docker/containers", m: "GET", t: "Operations", s: "List containers", d: "List all Docker containers with status" },
  { p: "/api/ops/docker/containers/{id}", m: "GET", t: "Operations", s: "Get container", d: "Detailed info for a specific Docker container" },
  { p: "/api/ops/docker/containers/{id}/action", m: "POST", t: "Operations", s: "Container action 🔒", d: "Start, stop, or restart a container (admin auth required)" },
  { p: "/api/ops/system", m: "GET", t: "Operations", s: "System metrics", d: "CPU, memory, disk usage" },
  { p: "/api/ops/system/processes", m: "GET", t: "Operations", s: "Processes", d: "List running ecosystem processes" },
  { p: "/api/ops/logs/{id}", m: "GET", t: "Operations", s: "Get logs", d: "Recent logs for a service (lines, since params)" },
  { p: "/api/ops/logs/{id}/stream", m: "GET", t: "Operations", s: "Stream logs (SSE)", d: "Real-time log streaming via SSE" },
  { p: "/api/ops/config", m: "GET", t: "Operations", s: "Ecosystem config", d: "Current ecosystem configuration" },
  { p: "/api/ops/contracts", m: "GET", t: "Operations", s: "List contracts", d: "All API contracts (OpenAPI specs)" },
  { p: "/api/ops/contracts/{id}", m: "GET", t: "Operations", s: "Get contract", d: "Specific API contract by ID" },
  { p: "/api/ops/health", m: "GET", t: "Operations", s: "Ops health", d: "Ops-dashboard service health" },

  /* ── 11. ARGUS Dashboard ───────────────────────────────────── */
  { p: "/api/argus-dashboard/data-sources", m: "GET", t: "ARGUS Dashboard", s: "Data sources", d: "Comprehensive info about all data directories" },
  { p: "/api/argus-dashboard/data-sources/{id}", m: "GET", t: "ARGUS Dashboard", s: "Data source detail", d: "Detailed info about a specific data source" },
  { p: "/api/argus-dashboard/data-sources/{id}/files/{path}", m: "GET", t: "ARGUS Dashboard", s: "File content", d: "Content of a specific file from a data source" },
  { p: "/api/argus-dashboard/stats", m: "GET", t: "ARGUS Dashboard", s: "Aggregate stats", d: "Aggregate statistics across all data sources" },
  { p: "/api/argus-dashboard/cases", m: "GET", t: "ARGUS Dashboard", s: "List cases", d: "All pipeline case executions" },
  { p: "/api/argus-dashboard/databases/overview", m: "GET", t: "ARGUS Dashboard", s: "Databases overview", d: "Overview of all databases used in ARGUS pipeline" },
  { p: "/api/argus-dashboard/databases/qdrant", m: "GET", t: "ARGUS Dashboard", s: "Qdrant DB info", d: "Detailed Qdrant vector database info" },
  { p: "/api/argus-dashboard/databases/neo4j", m: "GET", t: "ARGUS Dashboard", s: "Neo4j DB info", d: "Detailed Neo4j graph database info" },
  { p: "/api/argus-dashboard/databases/neo4j/live", m: "GET", t: "ARGUS Dashboard", s: "Neo4j live stats", d: "Real-time Neo4j graph statistics" },
  { p: "/api/argus-dashboard/databases/qdrant/sample", m: "GET", t: "ARGUS Dashboard", s: "Qdrant sample", d: "Sample data from Qdrant collection" },
  { p: "/api/argus-dashboard/pipeline-results", m: "GET", t: "ARGUS Dashboard", s: "Pipeline results", d: "Per-framework files from pipeline runs; defaults to most recent" },
  { p: "/api/argus-dashboard/pipeline-results/{id}/summary", m: "GET", t: "ARGUS Dashboard", s: "Run summary", d: "Structured summary with violations, legal arguments, and Mermaid graph" },
  { p: "/api/argus-dashboard/pipeline-results/{id}/neo4j-import", m: "POST", t: "ARGUS Dashboard", s: "Neo4j import", d: "Execute Neo4j import for a pipeline run using Cypher files" },
  { p: "/api/argus-dashboard/pipeline-results/{id}/export", m: "GET", t: "ARGUS Dashboard", s: "Export run (ZIP)", d: "Download all files for a pipeline run as ZIP" },
  { p: "/api/argus-dashboard/pipeline-results/import", m: "POST", t: "ARGUS Dashboard", s: "Import run (ZIP)", d: "Import a pipeline run ZIP into data/pipeline_results/" },
  { p: "/api/argus-dashboard/export", m: "GET", t: "ARGUS Dashboard", s: "Export all (ZIP)", d: "Bundle every data directory plus manifest into one ZIP" },
  { p: "/api/argus-dashboard/import", m: "POST", t: "ARGUS Dashboard", s: "Import all (ZIP)", d: "Restore dashboard data from exported ZIP" },
  { p: "/api/argus-dashboard/clean-all", m: "POST", t: "ARGUS Dashboard", s: "Clean all data", d: "Dry-run or execute full project data wipe (confirm=true to execute)" },
  { p: "/api/argus-dashboard/chat/models", m: "GET", t: "ARGUS Dashboard", s: "Chat models", d: "Available LLM models for dashboard chat" },
  { p: "/api/argus-dashboard/chat/context-load", m: "GET", t: "ARGUS Dashboard", s: "Load chat context", d: "Load data source or file content for chat context" },
  { p: "/api/argus-dashboard/chat/message", m: "POST", t: "ARGUS Dashboard", s: "Chat message", d: "Send chat message to local LLM with dashboard context" },
  { p: "/api/argus-dashboard/endpoint-scan", m: "POST", t: "ARGUS Dashboard", s: "Endpoint scan", d: "Scan project directory and return discovered endpoints" },

  /* ── 12. Transcription (Pinocchio) ─────────────────────────── */
  // Core
  { p: "api/diarization/health", m: "GET", t: "Transcription", s: "Service health", d: "Check whether the Pinocchio transcription service is running and healthy" },
  { p: "api/diarization/parameters", m: "GET", t: "Transcription", s: "Get diarization parameters", d: "Retrieve structured metadata for all available diarization parameters with types, defaults, and allowed values" },
  { p: "api/diarization/models/whisper", m: "GET", t: "Transcription", s: "List Whisper models", d: "List all available Whisper model sizes (tiny, base, small, medium, large)" },
  { p: "/api/diarization/transcribe", m: "POST", t: "Transcription", s: "Transcribe audio", d: "Transcribe full audio file with speaker diarization. Content-Type: multipart/form-data. Fields: file (binary, REQUIRED), language (string, e.g. en/pt/es), model_size (string, e.g. large). Returns complete transcript with speaker segments." },
  { p: "/api/diarization/transcribe/pyannote", m: "POST", t: "Transcription", s: "Transcribe (pyannote)", d: "Transcribe audio using pyannote.ai pipeline. Content-Type: multipart/form-data. Fields: file (binary, REQUIRED), language (string), model_size (string), min_speakers (int), max_speakers (int), vad_threshold (float 0-1), remove_silence (bool), noise_reduce (bool), word_timestamps (bool), initial_prompt (string), beam_size (int), best_of (int), whisper_temp (float)." },
  { p: "/api/diarization/transcribe", m: "POST", t: "Transcription", s: "Transcribe async", d: "Start an async transcription job and receive a job_id immediately; poll or stream its progress" },
  // Diarization & Excerpts
  { p: "api/diarization/excerpt", m: "POST", t: "Transcription", s: "Diarize excerpt", d: "Diarize a time range of an audio file. Content-Type: multipart/form-data. Fields: audio (file upload) OR file_path (string, server path like /root/vps_projects-main/LA8159-ai/pinocchio/data/audio/FILE.m4a), start (float, REQUIRED, seconds), end (float, REQUIRED, seconds), min_speakers (int, default 1), max_speakers (int, default 2), num_speakers (int|null). IMPORTANT: parameter names are start/end NOT start_time/end_time, field is audio NOT audio_file. Supports WAV, MP3, M4A." },
  { p: "api/diarization/excerpt-by-path", m: "POST", t: "Transcription", s: "Diarize excerpt by path", d: "Diarize a time range using a server-side file. Content-Type: application/json. Body: {file_path: string (REQUIRED, e.g. /root/vps_projects-main/LA8159-ai/pinocchio/data/audio/Pedro_Pablo_Dartnell_2.m4a), start: float (REQUIRED, seconds), end: float (REQUIRED, seconds), min_speakers: int (default 1), max_speakers: int (default 2), num_speakers: int|null}. IMPORTANT: params are file_path/start/end NOT audio_file_path/start_time/end_time. Auto-converts M4A/MP3 to WAV." },
  { p: "api/diarization/pyannote/files/{token}", m: "GET", t: "Transcription", s: "Get temporary audio file", d: "Retrieve a temporary public-facing audio file URL used internally by pyannote for processing" },
  // Voiceprints
  { p: "api/diarization/voiceprint_from_file", m: "POST", t: "Transcription", s: "Extract voiceprint", d: "Extract speaker voiceprint embedding from a time range. Content-Type: multipart/form-data. Fields: file (binary, REQUIRED), start (float, REQUIRED, seconds), end (float, REQUIRED, seconds), label (string, REQUIRED, e.g. Dr. Smith). Note: params are start/end NOT start_time/end_time." },
  { p: "api/diarization/identify_speakers", m: "POST", t: "Transcription", s: "Identify speakers", d: "Identify speakers by comparing against known voiceprints. Content-Type: multipart/form-data. Fields: file (binary, REQUIRED), voiceprints_json (string, REQUIRED, JSON array of {label, voiceprint}), threshold (int, 0-100), exclusive (bool)." },
  // Transcript Management
  { p: "api/diarization/transcripts", m: "GET", t: "Transcription", s: "List transcripts", d: "List all transcript IDs stored on the server" },
  { p: "api/diarization/transcripts/{transcript_id}", m: "GET", t: "Transcription", s: "Get transcript", d: "Load the full transcript data for a specific transcript including all segments, speaker labels, and timestamps" },
  { p: "api/diarization/transcripts/analyze", m: "POST", t: "Transcription", s: "Analyze transcript", d: "Run Claude AI analysis on a stored transcript. Content-Type: application/json. Body: {transcript_id: string (REQUIRED), instructions: string (REQUIRED, analysis prompt)}." },
  { p: "api/diarization/transcripts/search", m: "POST", t: "Transcription", s: "Search transcripts", d: "Semantic search across indexed transcripts via Qdrant. Content-Type: application/json. Body: {query: string (REQUIRED), limit: int (default 10)}." },
  { p: "api/diarization/transcripts/{transcript_id}/index", m: "POST", t: "Transcription", s: "Index transcript", d: "Manually index or re-index a specific transcript into Qdrant to make it searchable" },
  { p: "api/diarization/transcripts/index-all", m: "POST", t: "Transcription", s: "Index all transcripts", d: "Re-index all stored transcripts into Qdrant; admin/maintenance operation to rebuild the full search index" },
  // Async Jobs
  { p: "api/diarization/transcripts/status/{job_id}", m: "GET", t: "Transcription", s: "Get job status", d: "Fetch current status of an async transcription job including progress percentage and stage" },
  { p: "api/diarization/transcripts/stream/{job_id}", m: "GET", t: "Transcription", s: "Stream job progress (SSE)", d: "Stream real-time progress events for an async transcription job via Server-Sent Events" },
  // Persistence & Snapshots
  { p: "api/diarization/persistence/snapshots", m: "POST", t: "Transcription", s: "Save snapshot", d: "Persist a complete Pinocchio session bundle (transcript, speaker labels, voiceprints, analyses, metadata) as a named snapshot" },
  { p: "api/diarization/persistence/snapshots", m: "GET", t: "Transcription", s: "List snapshots", d: "List all persisted Pinocchio snapshots ordered by most recent" },
  { p: "api/diarization/persistence/snapshots/{snapshot_id}", m: "GET", t: "Transcription", s: "Get snapshot manifest", d: "Retrieve the manifest (metadata, file listing, timestamps) for a specific snapshot" },
  { p: "api/diarization/persistence/snapshots/{snapshot_id}/bundle", m: "GET", t: "Transcription", s: "Load snapshot bundle", d: "Load the full data bundle for a persisted snapshot to restore a complete session state" },
  { p: "api/diarization/persistence/snapshots/{snapshot_id}/audio", m: "GET", t: "Transcription", s: "Download snapshot audio", d: "Download the source audio file associated with a persisted snapshot" },
  { p: "api/diarization/persistence/snapshots/{snapshot_id}/zip", m: "GET", t: "Transcription", s: "Download snapshot ZIP", d: "Download a complete snapshot as a ZIP archive including transcript, labels, voiceprints, analyses, metadata, and optional audio" },
  // Segment Export
  { p: "api/diarization/segment-package", m: "POST", t: "Transcription", s: "Download segment package", d: "Extract and download a single transcript segment as a self-contained package with clipped audio and metadata" },

  /* ── 13. Garage Assistants API ─────────────────────────────── */
  { p: "/api/garage/health", m: "GET", t: "Garage", s: "Service health", d: "Garage assistants service health" },
  { p: "/api/garage/models", m: "GET", t: "Garage", s: "List models", d: "Available models from Ollama + DeepSeek" },
  { p: "/api/garage/chat/completions", m: "POST", t: "Garage", s: "Chat completions", d: "Enhanced OpenAI-compatible chat with file context and tool support" },
  { p: "/api/garage/files", m: "GET", t: "Garage", s: "List files", d: "List uploaded files, optionally filtered by purpose" },
  { p: "/api/garage/files", m: "POST", t: "Garage", s: "Upload file", d: "Upload a file for use with assistants (multipart)" },
  { p: "/api/garage/files/summarize", m: "POST", t: "Garage", s: "Summarize files", d: "Summarize multiple files using AI" },
  { p: "/api/garage/assistants", m: "GET", t: "Garage", s: "List assistants", d: "List all configured assistants" },
  { p: "/api/garage/assistants", m: "POST", t: "Garage", s: "Create assistant", d: "Create a new assistant with specified configuration" },
  { p: "/api/garage/assistants/{id}", m: "GET", t: "Garage", s: "Get assistant", d: "Retrieve assistant details by ID" },
  { p: "/api/garage/assistants/{id}", m: "PATCH", t: "Garage", s: "Update assistant", d: "Update assistant configuration" },
  { p: "/api/garage/assistants/{id}", m: "DELETE", t: "Garage", s: "Delete assistant", d: "Delete an assistant" },
  { p: "/api/garage/assistants/{id}/chat", m: "POST", t: "Garage", s: "Assistant chat", d: "Send a chat message to a specific assistant" },
  { p: "/api/garage/qdrant/collections", m: "GET", t: "Garage", s: "Qdrant collections", d: "List all Qdrant vector collections" },
  { p: "/api/garage/qdrant/collections", m: "POST", t: "Garage", s: "Create Qdrant collection", d: "Create a new Qdrant vector collection" },
  { p: "/api/garage/qdrant/collections/{name}", m: "DELETE", t: "Garage", s: "Delete Qdrant collection", d: "Delete a Qdrant collection" },
  { p: "/api/garage/qdrant/collections/{name}/ingest", m: "POST", t: "Garage", s: "Qdrant ingest files", d: "Ingest files into a Qdrant collection (multipart)" },
  { p: "/api/garage/qdrant/search", m: "POST", t: "Garage", s: "Qdrant search", d: "Vector similarity search across collections" },
  { p: "/api/garage/qdrant/query", m: "POST", t: "Garage", s: "Qdrant query", d: "Query Qdrant vector store" },
  { p: "/api/garage/knowledge/query", m: "POST", t: "Garage", s: "Knowledge query", d: "Query knowledge base with semantic search" },
  { p: "/api/garage/knowledge/ingest/text", m: "POST", t: "Garage", s: "Ingest text", d: "Ingest text content into knowledge base" },
  { p: "/api/garage/knowledge/ingest/file", m: "POST", t: "Garage", s: "Ingest file", d: "Ingest file into knowledge base (multipart)" },
  { p: "/api/garage/tools", m: "GET", t: "Garage", s: "List tools", d: "List all available tools/functions" },
  { p: "/api/garage/tools/execute", m: "POST", t: "Garage", s: "Execute tool", d: "Execute a tool/function by name with parameters" },
  { p: "/api/garage/ingestion/ingest-directory", m: "POST", t: "Garage", s: "Ingest directory", d: "Ingest all files from a directory into knowledge base" },
  { p: "/api/garage/ingestion/ingest-file", m: "POST", t: "Garage", s: "Ingest single file", d: "Ingest a single file into knowledge base (multipart)" },
  { p: "/api/garage/ingestion/search", m: "POST", t: "Garage", s: "Search ingested", d: "Search across ingested documents" },

  /* ── 14. Qdrant Vector Database ────────────────────────────── */
  { p: "/api/qdrant/health", m: "GET", t: "Qdrant", s: "Health check", d: "Check Qdrant service health and connection status" },
  { p: "/api/qdrant/status", m: "GET", t: "Qdrant", s: "Service status", d: "Overall status with embedding model information" },
  { p: "/api/qdrant/collections", m: "GET", t: "Qdrant", s: "List collections", d: "All collections in Qdrant with metadata" },
  { p: "/api/qdrant/collections", m: "POST", t: "Qdrant", s: "Create collection", d: "Create new vector collection with configuration" },
  { p: "/api/qdrant/collections/{name}", m: "DELETE", t: "Qdrant", s: "Delete collection", d: "Permanently delete collection and all data" },
  { p: "/api/qdrant/collections/{name}/info", m: "GET", t: "Qdrant", s: "Collection info", d: "Detailed information about a specific collection" },
  { p: "/api/qdrant/collections/{name}/ingest/file", m: "POST", t: "Qdrant", s: "Ingest file", d: "Upload and ingest file into collection (PDF, TXT, JSON)" },
  { p: "/api/qdrant/collections/{name}/ingest/structured", m: "POST", t: "Qdrant", s: "Ingest structured", d: "Ingest structured JSON data (transcripts, violations, laws)" },
  { p: "/api/qdrant/collections/{name}/ingest/batch", m: "POST", t: "Qdrant", s: "Batch ingest", d: "Batch ingest multiple files in a single request" },
  { p: "/api/qdrant/search", m: "POST", t: "Qdrant", s: "Semantic search", d: "Semantic search on a collection using text query" },
  { p: "/api/qdrant/collections/{name}/query/vector", m: "POST", t: "Qdrant", s: "Vector query", d: "Direct vector similarity search without text encoding" },
  { p: "/api/qdrant/collections/{name}/cross-reference", m: "POST", t: "Qdrant", s: "Cross-reference", d: "Cross-reference content with regulations and return matches" },
  { p: "/api/qdrant/collections/{name}/points", m: "GET", t: "Qdrant", s: "List points", d: "List points in a collection with pagination" },
  { p: "/api/qdrant/collections/{name}/points", m: "DELETE", t: "Qdrant", s: "Delete points", d: "Delete specific points by IDs" },
  { p: "/api/qdrant/knowledge/collection/{name}/clear", m: "DELETE", t: "Qdrant", s: "Clear collection", d: "Remove all points without deleting the collection" },
  { p: "/api/qdrant/vectors/store", m: "POST", t: "Qdrant", s: "Store vector", d: "Store agent interaction or knowledge in vector store" },
  { p: "/api/qdrant/vectors/search", m: "POST", t: "Qdrant", s: "Vectors search", d: "Semantic search across agent memory and knowledge base" },
  { p: "/api/qdrant/vectors/agent/{id}", m: "GET", t: "Qdrant", s: "Agent memory", d: "Retrieve agent conversation history and memory" },
  { p: "/api/qdrant/vectors/agent/{id}/clear", m: "DELETE", t: "Qdrant", s: "Clear agent memory", d: "Clear all or part of agent's memory" },
  { p: "/api/qdrant/vectors/documents/ingest", m: "POST", t: "Qdrant", s: "Ingest for agent", d: "Ingest document into agent's knowledge base" },
  { p: "/api/qdrant/vectors/agent/{id}/rag", m: "POST", t: "Qdrant", s: "RAG retrieve", d: "Retrieve context for Retrieval-Augmented Generation" },
  { p: "/api/qdrant/vectors/agent/{id}/stats", m: "GET", t: "Qdrant", s: "Agent memory stats", d: "Detailed statistics about agent's memory usage" },
  { p: "/api/qdrant/metadata/directory", m: "GET", t: "Qdrant", s: "Metadata files", d: "List metadata files in the metadata directory" },
  { p: "/api/qdrant/metadata/file/{filename}", m: "GET", t: "Qdrant", s: "Get metadata file", d: "Retrieve content of a metadata file" },
  { p: "/api/qdrant/metadata/file/{filename}", m: "POST", t: "Qdrant", s: "Update metadata file", d: "Update or create a metadata file" },
  { p: "/api/qdrant/metadata/file/{filename}", m: "DELETE", t: "Qdrant", s: "Delete metadata file", d: "Delete a metadata file" },
  { p: "/api/qdrant/metadata/search", m: "POST", t: "Qdrant", s: "Search metadata", d: "Search through metadata files for specific content" },
  { p: "/api/qdrant/metadata/collection/{name}", m: "GET", t: "Qdrant", s: "Collection metadata", d: "Get metadata associated with a Qdrant collection" },
  { p: "/api/qdrant/metadata/collection/{name}/metadata", m: "POST", t: "Qdrant", s: "Update collection meta", d: "Store or update custom metadata for a collection" },
  { p: "/api/qdrant/version", m: "GET", t: "Qdrant", s: "Version", d: "Qdrant service version and dependency information" },
  { p: "/api/qdrant/config", m: "GET", t: "Qdrant", s: "Configuration", d: "Current Qdrant service configuration (safe details only)" },

  /* ── 15. Shared Layer ──────────────────────────────────────── */
  { p: "/api/shared/health", m: "GET", t: "Shared Layer", s: "Health check", d: "Shared layer service health" },
  { p: "/api/shared/agents", m: "GET", t: "Shared Layer", s: "List agents", d: "All agent definitions from the shared layer" },
  { p: "/api/shared/agents/{id}", m: "GET", t: "Shared Layer", s: "Get agent", d: "Specific agent definition" },
  { p: "/api/shared/contracts", m: "GET", t: "Shared Layer", s: "List contracts", d: "All API contracts" },
  { p: "/api/shared/contracts/{id}", m: "GET", t: "Shared Layer", s: "Get contract", d: "Specific API contract" },
  { p: "/api/shared/law", m: "GET", t: "Shared Layer", s: "List law frameworks", d: "All legal frameworks in the shared layer" },
  { p: "/api/shared/law/{code}", m: "GET", t: "Shared Layer", s: "Get law framework", d: "Specific legal framework by code" },
  { p: "/api/shared/law/{code}/{article}", m: "GET", t: "Shared Layer", s: "Get law article", d: "Specific article within a legal framework" },
  { p: "/api/shared/corpus", m: "GET", t: "Shared Layer", s: "List corpus", d: "All corpus categories" },
  { p: "/api/shared/corpus/{category}", m: "GET", t: "Shared Layer", s: "Get corpus category", d: "Corpus entries for a specific category" },
  { p: "/api/shared/ontology", m: "GET", t: "Shared Layer", s: "List ontology", d: "Ontology files" },
  { p: "/api/shared/ontology/{file}", m: "GET", t: "Shared Layer", s: "Get ontology file", d: "Specific ontology file" },
  { p: "/api/shared/docs", m: "GET", t: "Shared Layer", s: "List docs", d: "Shared documentation" },
  { p: "/api/shared/scopes", m: "GET", t: "Shared Layer", s: "List scopes", d: "Shared scopes (workspace client compatibility)" },
  { p: "/api/shared/content", m: "GET", t: "Shared Layer", s: "Get content", d: "Shared content by category (compatibility)" },
  { p: "/api/shared/file", m: "GET", t: "Shared Layer", s: "Get file", d: "Specific shared file (compatibility)" },
  { p: "/api/shared/ecosystem", m: "GET", t: "Shared Layer", s: "Ecosystem registry", d: "Ecosystem service registry" },

  /* ── 16. TheBridge ─────────────────────────────────────────── */
  { p: "/api/bridge/health", m: "GET", t: "TheBridge", s: "Bridge health", d: "TheBridge service health check" },
  { p: "/api/bridge/organize", m: "POST", t: "TheBridge", s: "Organize directory", d: "Rebuild case-server endpoints from a new directory" },
  { p: "/api/bridge/upload", m: "POST", t: "TheBridge", s: "Upload files", d: "Save uploaded files locally and rebuild case-server index" },
  { p: "/api/bridge/search", m: "GET", t: "TheBridge", s: "Search documents", d: "Search across documents (q=, limit=)" },
  { p: "/api/bridge/manifest", m: "GET", t: "TheBridge", s: "Document manifest", d: "Get the document manifest" },
  { p: "/api/bridge/categories", m: "GET", t: "TheBridge", s: "Categories", d: "Get document categories" },
  { p: "/api/bridge/files", m: "GET", t: "TheBridge", s: "List files", d: "List files with optional filters: category, ext, kind, group" },
  { p: "/api/bridge/inventory", m: "GET", t: "TheBridge", s: "Live inventory", d: "Live file inventory from case-server with full metadata" },
  { p: "/api/bridge/tree", m: "GET", t: "TheBridge", s: "Directory tree", d: "Get directory tree from case-server" },
  { p: "/api/bridge/file-detail", m: "GET", t: "TheBridge", s: "File detail", d: "Enriched file detail: metadata, preview, tags, entity mentions" },
  { p: "/api/bridge/raw", m: "GET", t: "TheBridge", s: "Raw file", d: "Stream raw bytes of an indexed file" },
  { p: "/api/bridge/pipeline/stats", m: "GET", t: "TheBridge", s: "Pipeline stats", d: "Pipeline run statistics" },
  { p: "/api/bridge/pipeline/entities", m: "GET", t: "TheBridge", s: "Pipeline entities", d: "Global entity index (people, laws, organizations, locations, dates)" },
  { p: "/api/bridge/pipeline/relationships", m: "GET", t: "TheBridge", s: "Relationships", d: "Cross-file relationships (min_strength=)" },
  { p: "/api/bridge/pipeline/timeline", m: "GET", t: "TheBridge", s: "Pipeline timeline", d: "Chronological timeline (from=, to=)" },
  { p: "/api/bridge/pipeline/search", m: "GET", t: "TheBridge", s: "Pipeline search", d: "Deep pipeline search (q=)" },
  { p: "/api/bridge/intelligence/run", m: "POST", t: "TheBridge", s: "Run intelligence", d: "Run intelligence analysis (L5–L7)" },
  { p: "/api/bridge/intelligence/run-stream", m: "GET", t: "TheBridge", s: "Intelligence stream (SSE)", d: "Intelligence analysis SSE stream (L5–L7)" },
  { p: "/api/bridge/intelligence/summary", m: "GET", t: "TheBridge", s: "Intelligence summary", d: "Latest intelligence summary" },
  { p: "/api/bridge/intelligence/case-graph", m: "GET", t: "TheBridge", s: "Case graph", d: "Full case graph" },
  { p: "/api/bridge/intelligence/violations", m: "GET", t: "TheBridge", s: "Violations", d: "Violations list (severity=, min_confidence=)" },
  { p: "/api/bridge/intelligence/timeline", m: "GET", t: "TheBridge", s: "Intelligence timeline", d: "Intelligence timeline" },
  { p: "/api/bridge/intelligence/gap-report", m: "GET", t: "TheBridge", s: "Gap report", d: "Missing evidence and coverage gaps" },
  { p: "/api/bridge/events", m: "GET", t: "TheBridge", s: "Events", d: "Formalized events (type=incident|complaint|…)" },
  { p: "/api/bridge/events/graph", m: "GET", t: "TheBridge", s: "Events graph", d: "Causal/temporal event graph (edge_type=)" },
  { p: "/api/bridge/case-state", m: "GET", t: "TheBridge", s: "Case state", d: "Full case state evaluation" },
  { p: "/api/bridge/case-state/phase", m: "GET", t: "TheBridge", s: "Case phase", d: "Current case phase" },
  { p: "/api/bridge/case-state/findings", m: "GET", t: "TheBridge", s: "Findings", d: "Anomalies and gaps (severity=, type=)" },
  { p: "/api/bridge/case-state/next-steps", m: "GET", t: "TheBridge", s: "Next steps", d: "Recommended next actions" },
  { p: "/api/bridge/comprehend/run", m: "POST", t: "TheBridge", s: "Run comprehension", d: "Run comprehension Layer C analysis" },
  { p: "/api/bridge/comprehend/run-stream", m: "GET", t: "TheBridge", s: "Comprehend stream (SSE)", d: "Comprehension SSE stream (Layer C)" },
  { p: "/api/bridge/comprehend/overview", m: "GET", t: "TheBridge", s: "Comprehend overview", d: "Full corpus understanding" },
  { p: "/api/bridge/comprehend/guide", m: "GET", t: "TheBridge", s: "Corpus guide", d: "Human-readable corpus guide (format=md)" },
  { p: "/api/bridge/comprehend/groups", m: "GET", t: "TheBridge", s: "Comprehend groups", d: "Per-category descriptions (domain=)" },
  { p: "/api/bridge/comprehend/strategies", m: "GET", t: "TheBridge", s: "Strategies", d: "Organisation strategies" },

  /* ── 17. TJRS Jurisprudence ────────────────────────────────── */
  { p: "/api/tjrs/health", m: "GET", t: "TJRS", s: "TJRS health", d: "TJRS jurisprudence service health" },
  { p: "/api/tjrs/stats", m: "GET", t: "TJRS", s: "Usage stats", d: "Service usage statistics" },
  { p: "/api/tjrs/search", m: "POST", t: "TJRS", s: "Search cases", d: "Search TJRS court system; returns matching cases with inteiro teor links" },
  { p: "/api/tjrs/download", m: "POST", t: "TJRS", s: "Download document", d: "Download a single inteiro teor document from TJRS" },
  { p: "/api/tjrs/download-batch", m: "POST", t: "TJRS", s: "Batch download", d: "Batch download multiple inteiro teor documents" },

  /* ── 18. Functions Registry ────────────────────────────────── */
  { p: "/api/functions/index", m: "GET", t: "Functions Registry", s: "Function index", d: "Generated function index grouped by category (9 categories)" },
  { p: "/api/functions/capabilities", m: "GET", t: "Functions Registry", s: "Capability map", d: "by_capability, by_use_case, and workflows groupings" },
  { p: "/api/functions/diagram", m: "GET", t: "Functions Registry", s: "Mermaid diagram", d: "Pre-built Mermaid flowchart of frontend → API wiring" },
  { p: "/api/functions/{id}", m: "GET", t: "Functions Registry", s: "Function detail", d: "Individual function's full JSON schema" },

  /* ── 19. RunPod Workspace (CEL) ─────────────────────────────── */
  { p: "/api/runpod/workspaces", m: "POST", t: "RunPod Workspace", s: "Create workspace", d: "Deploy a new GPU workspace to RunPod" },
  { p: "/api/runpod/workspaces/{id}", m: "GET", t: "RunPod Workspace", s: "Get workspace", d: "Get workspace details by provider ID" },
  { p: "/api/runpod/workspaces/{id}/status", m: "GET", t: "RunPod Workspace", s: "Workspace status", d: "Check workspace provisioning/running status" },
  { p: "/api/runpod/workspaces/{id}/stop", m: "POST", t: "RunPod Workspace", s: "Stop workspace", d: "Stop a running workspace" },
  { p: "/api/runpod/workspaces/{id}", m: "DELETE", t: "RunPod Workspace", s: "Destroy workspace", d: "Terminate and destroy workspace" },
  { p: "/api/runpod/gpus", m: "GET", t: "RunPod Workspace", s: "GPU options", d: "List available GPU types with pricing" },
  { p: "/api/runpod/validate", m: "POST", t: "RunPod Workspace", s: "Validate credentials", d: "Validate RunPod API key" }
];

// Base URL defaults: local dev uses same-origin, remote deploy uses same-origin gateway paths.
(function () {
  var gateway = window.location.origin;

  var defaults = {
    gateway: gateway,
    bridge: gateway + '/api/bridge',
    qdrant: gateway + '/api/qdrant',
    transcription: gateway + '/api/pinocchio',
    argus: gateway + '/api/pipeline',
    garage: gateway + '/api/garage',
    shared: gateway + '/api/shared',
    runpod: gateway + '/api/runpod'
  };

  window.Olivia_BASE_URLS = window.Olivia_BASE_URLS || {};
  Object.keys(defaults).forEach(function (k) {
    if (!window.Olivia_BASE_URLS[k]) window.Olivia_BASE_URLS[k] = defaults[k];
  });
})();
